### ISSUE TITLE
Issues when compiling with latest zig version

### ISSUE THREAD

**Issue by joachimschmidt557** [tiehuis/zig-regex#1]
I'm building zig from the master branch. Currently I'm encountering errors when trying to build `zig-regex` or incorporating it in another zig project.

This is the error which is triggered when compiling:

![image](https://user-images.githubusercontent.com/28556218/59526416-2c12fc80-8ed9-11e9-98e2-231ff0fca5a1.png)

**Comment by tiehuis** [comment]
@joachimschmidt557 Thanks for letting me know. Now fixed.
