### ISSUE TITLE
Add build.zig.zon package support

### ISSUE THREAD

**Issue by softprops** [tiehuis/zig-regex#27]
Zig 0.11 introduced a native package management system to consume third party zig libraries. 

The zig community really needs a regex library and this looks like the closest thing to one (thank you for that)

I would like to be able to consume this library through that native package management system

**Comment by tiehuis** [comment]
Added in https://github.com/tiehuis/zig-regex/commit/3bb7dbafb5ab48d44700abce56506b2471778264.

Feel free to open any follow-ups if there are further improvements (e.g. releases added etc).

**Comment by softprops** [comment]
Sweet! Thank you so much for this library. I'm new to zig and libraries for things like working with regexes are foundational. I'm so relieved this library exists
