### ISSUE TITLE
Please create a `.tar.gz` for us to reference

### ISSUE THREAD

**Issue by iiian** [tiehuis/zig-regex#29]
Currently, `zon` requires a `tar.gz` target if you want to use other people's projects *(you down with OPP? yeah you know me)*.

I'm new to `Zig`, so maybe I'm just #doing-it-wrong, but if you agree with me, is this something you could throw together in a releases job? Otherwise AFAICT I have to download this project locally.

Thanks!

**Comment by iiian** [comment]
I figured it out. 

`https://github.com/tiehuis/zig-regex/archive/<commit-hash-of-master>.tar.gz`

Pay this no mind.

**Comment by tiehuis** [comment]
Created a new issue about automating this for tagged releases via ci since this would still be an improvement. #30.

**Comment by iiian** [comment]
You might even solicit around the `ziglang` Discord and see what other people are doing, too. I've seen multiple instances of people doing the `/archive/<commit-hash>.tar.gz` pattern, and then even ChatGPT suggested it. In any case, thanks for listening and for a prompt response, sir.
